### ISSUE TITLE
How to use this image to run ffmpeg command

### ISSUE THREAD

**Issue by TylerJackk** [alfg/docker-ffmpeg#11]
Hi, I'd like to know how to use current docker image to run a command like `ffmpeg -i video_url -c copy video.mp4`
Already have pulled the image
`docker images`
`REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE`
`alfg/ffmpeg          latest              0c408f4d8216        4 weeks ago         106MB`

**Comment by alfg** [comment]
Hey @TylerJackk, 

You can try running the command while mounting a volume to access your local files:
```
docker run -v ${PWD}:/opt/tmp/ -it --rm alfg/ffmpeg ffprobe /opt/tmp/video.mp4
```

```
docker run -v ${PWD}:/opt/tmp/ -it --rm alfg/ffmpeg ffmpeg -i /opt/tmp/video.mp4 -c copy video-out.mp4
```

**Comment by TylerJackk** [comment]
Cool, worked for me.
will close this issue
thanks!
