### ISSUE TITLE
Error loading shared library librav1e.so

### ISSUE THREAD

**Issue by etix** [alfg/docker-ffmpeg#13]
Hi,

Latest image update broke at least ffprobe. `rav1e` library is not found.

```
Error loading shared library librav1e.so: No such file or directory (needed by /opt/ffmpeg/bin/ffprobe)
Error relocating /opt/ffmpeg/bin/ffprobe: rav1e_twopass_in: symbol not found
Error relocating /opt/ffmpeg/bin/ffprobe: rav1e_data_unref: symbol not found
...
```

**Comment by etix** [comment]
It seems the symlink from `/usr/lib/librav1e.so.0` to `/usr/lib/librav1e.so` is missing.

**Comment by alfg** [comment]
Hey @etix, 
Thanks for catching this. I'll add a fix soon.

**Comment by alfg** [comment]
Fixed on main and snapshot. Also updated to Alpine 1.13. Thanks!
https://github.com/alfg/docker-ffmpeg/commit/d577f0918a3f1382b9722c866d16c430a11d7024
