### ISSUE TITLE
fdk-aac-dev missing at step "Get fdk-aac from testing"

### ISSUE THREAD

**Issue by needfortri** [alfg/docker-ffmpeg#9]
Hi,
Since 2 weeks it appears `apk add --update fdk-aac-dev` step is broken : 
I get the following error when building from Dockerfile : 

```
 RUN echo http://dl-cdn.alpinelinux.org/alpine/edge/testing >> /etc/apk/repositories &&   apk add --update fdk-aac-dev
 ---> Running in 3afd3b6ead37
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  fdk-aac-dev (missing):
    required by: world[fdk-aac-dev]
```

Is there an alternative to http://dl-cdn.alpinelinux.org/alpine/edge/testing in order to make it work again please ?
Thanks !

**Comment by alfg** [comment]
Hi @needfortri,

I believe it's due to `fdk-aac-dev` moving from `testing` repository to `community` recently. I'll add a fix soon.

**Comment by alfg** [comment]
Fixed. https://github.com/alfg/docker-ffmpeg/commit/2f7553dfef309533ec9a67225adc4bfecbccccdb
